# Site settings
title:       Web Developer & Designer
email:       info@danbdesigns.co.uk
author:      Daniel Broughton
description: "Dan B is a creative Web Developer & Designer from the midlands."
baseurl:     ""
url:         "http://danbdesigns.co.uk"
date_format: "%b %-d, %Y"

# Google services
google_analytics: UA-42270530-2
google_verification: google48201b4269d01271

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: DannnB
bitbucket_username:
stackoverflow_id:
twitter_username: DanBDesigns
google_plus_id:
linkedin_username: daniel-broughton-5797716a
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /blog/:year/:month/:day/:title.html # default: pretty
gems: ["jekyll-paginate","jekyll-sitemap"] # ,"octopress-minify-html"
paginate: 4
paginate_path: "page:num"
sass:
  compressed: true